title:            Ljhero
description:      Aha, Ljhero is on the road.
url:              http://ljhero.info
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          Ljhero
disqus_shortname: ljhero
google_analytics_id: 'UA-29456939-2'

links:
  - name:         About
    url:          /about
  - name:         Feed
    url:          /feed.xml
  - name:         Blog
    url:          http://ljhero.info
    external:     true
  - name:         Twitter
    url:          https://twitter.com/ljhero
    external:     true
  - name:         GitHub
    url:          http://github.com/ljhero
    external:     true

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
